### ISSUE TITLE
SPC SPC mapping

### ISSUE THREAD

**Issue by dmitriyK1** [bling/dotemacs#15]
Hi!
I've seen that you use double SPC mapping but I wasn't able to figure out how this could be achieved without using your config
Can you give me an advice how can I bind execute-extended-command to SPC SPC with minimal configuration?
Thanks in advance.

**Comment by bling** [comment]
just need to do a `(define-key evil-normal-state-map (kbd "SPC SPC") #'execute-extended-command)`
