### ISSUE TITLE
suggestion for setting proxy?

### ISSUE THREAD

**Issue by whatacold** [bling/dotemacs#16]
Hi,
  I tried to put proxy settings in custom.el as below as in https://www.reddit.com/r/emacs/comments/3cfk3f/setting_proxy/:

    (setq url-proxy-services
          '(("http"     . "http://proxy.example.com:8080")
            ("https"    . "http://proxy.example.com:8080")
            ("ftp"      . "proxy.example.com:8080")
            ("no_proxy" . "^.*example.com")))

but it didn't work, on Windows.

Any suggestions? thanks.

**Comment by whatacold** [comment]
my emacs version is 25.2.1, and `url-proxy-services` variable exists only after (require 'url-vars).
but i am not sure where should i put these settings.

i just hard coded these in init.el for a test:
    (require 'url-vars)
    (setq url-proxy-services
     '(("no_proxy" . "^\\(localhost\\|10.*\\)")
       ("http" . "http://dev-proxy.oa.com:8080")
       ("https" . "http://dev-proxy.oa.com:8080")))
    
    (setq package-enable-at-startup nil)
    (package-initialize)

but it didn't work, emacs seems like block somewhere and can't finish loading scripts.

**Comment by whatacold** [comment]
Hi,
  It turned out that there must be no scheme specified, that is:

    (require 'url-vars)
    (setq url-proxy-services
     '(("no_proxy" . "^\\(localhost\\|10.*\\)")
       ("http" . "ip:8080")
       ("https" . "ip:8080")))
    
    (setq package-enable-at-startup nil)
    (package-initialize)

The proxy setting works now, then where would you suggest to put this configure?
Thanks.

**Comment by bling** [comment]
in work environments i typically do something like this:

~/AppData/Roaming/.emacs.d/init.el

    (setq user-emacs-directory "c:/path/to/local/drive/so/it/is/not/replicated/")
    ;; proxy config
    (load (concat user-emacs-directory "init.el"))
