### ISSUE TITLE
Autocomplete + Evil = Error

### ISSUE THREAD

**Issue by LukeMauldin** [bling/dotemacs#7]
When disabling company mode and enabling auto-complete (along with Evil) and attempting to use auto-complete in a text buffer I receive this error:
split-string: Wrong type argument: stringp, nil
Error in post-command-hook (evil-repeat-post-hook): (wrong-type-argument number-or-marker-p nil)

**Comment by bling** [comment]
works fine over here....it was probably just a temporary glitch.

**Comment by hotpxl** [comment]
Strange. I'm having this problem with `company-mode` and `evil-mode`. Open `*Messages*` to see the output. It happens only during my first completion. And happens when I hit <kbd>tab</kbd> too fast.
